=== oussamaelbouenani/ProjetSD2/countries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="cca3">
		<xs:restriction base="xs:ID">
			<xs:pattern value="\D{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="region">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Americas"/>
			<xs:enumeration value="Asia"/>
			<xs:enumeration value="Africa"/>
			<xs:enumeration value="Europe"/>
			<xs:enumeration value="Oceania"/>
			<xs:enumeration value="Antarctic"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="countries">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="country" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="border" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded">
							</xs:element>
						</xs:sequence>
						<xs:attribute name="capital" type="xs:string"/>
						<xs:attribute name="cca3" type="cca3" use="required"/>
						<xs:attribute name="currency" type="xs:string"/>
						<xs:attribute name="languages" type="xs:string"/>
						<xs:attribute name="latlng" type="xs:string" use="required"/>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="population" type="xs:nonNegativeInteger" use="required"/>
						<xs:attribute name="region" type="region" use="required"/>
						<xs:attribute name="subregion" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== oussamaelbouenani/ProjetSD2/countries.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<countries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="countries.xsd">
	<country capital="Oranjestad" cca3="ABW" currency="AWG"
		languages="Dutch,Papiamento" latlng="12.5,-69.96666666" name="Aruba"
		population="101484" region="Americas" subregion="Caribbean"/>
	<country capital="Kabul" cca3="AFG" currency="AFN"
		languages="Dari,Pashto,Turkmen" latlng="33,65" name="Afghanistan"
		population="25500100" region="Asia" subregion="Southern Asia">
		<border>IRN</border>
		<border>PAK</border>
		<border>TKM</border>
		<border>UZB</border>
		<border>TJK</border>
		<border>CHN</border>
	</country>
	<country capital="Luanda" cca3="AGO" currency="AOA"
		languages="Portuguese" latlng="-12.5,18.5" name="Angola"
		population="20609294" region="Africa" subregion="Middle Africa">
		<border>COG</border>
		<border>COD</border>
		<border>ZMB</border>
		<border>NAM</border>
	</country>
	<country capital="The Valley" cca3="AIA" currency="XCD"
		languages="English" latlng="18.25,-63.16666666" name="Anguilla"
		population="13452" region="Americas" subregion="Caribbean" />
	<country capital="Mariehamn" cca3="ALA" currency="EUR"
		languages="Swedish" latlng="60.116667,19.9" name="Åland Islands"
		population="28502" region="Europe" subregion="Northern Europe" />
	<country capital="Tirana" cca3="ALB" currency="ALL"
		languages="Albanian" latlng="41,20" name="Albania"
		population="2821977" region="Europe" subregion="Southern Europe">
		<border>MNE</border>
		<border>GRC</border>
		<border>MKD</border>
	</country>
	<country capital="Andorra la Vella" cca3="AND" currency="EUR"
		languages="Catalan" latlng="42.5,1.5" name="Andorra"
		population="76246" region="Europe" subregion="Southern Europe">
		<border>FRA</border>
		<border>ESP</border>
	</country>
	<country capital="Abu Dhabi" cca3="ARE" currency="AED"
		languages="Arabic" latlng="24,54" name="United Arab Emirates"
		population="5473972" region="Asia" subregion="Western Asia">
		<border>OMN</border>
		<border>SAU</border>
	</country>
	<country capital="Buenos Aires" cca3="ARG" currency="ARS"
		languages="Guaraní,Spanish" latlng="-34,-64" name="Argentina"
		population="40117096" region="Americas" subregion="South America">
		<border>BOL</border>
		<border>BRA</border>
		<border>CHL</border>
		<border>PRY</border>
		<border>URY</border>
	</country>
	<country capital="Yerevan" cca3="ARM" currency="AMD"
		languages="Armenian" latlng="40,45" name="Armenia"
		population="3024100" region="Asia" subregion="Western Asia">
		<border>AZE</border>
		<border>GEO</border>
		<border>IRN</border>
		<border>TUR</border>
	</country>
	<country capital="Pago Pago" cca3="ASM" currency="USD"
		languages="English,Samoan" latlng="-14.33333333,-170"
		name="American Samoa" population="55519" region="Oceania"
		subregion="Polynesia" />
	<country cca3="ATA" latlng="-90,0" name="Antarctica"
		population="0" region="Antarctic" />
	<country capital="Port-aux-Français" cca3="ATF" currency="EUR"
		languages="French" latlng="-49.25,69.167"
		name="French Southern and Antarctic Lands" population="140"
		region="Antarctic" />
	<country capital="Saint John's" cca3="ATG" currency="XCD"
		languages="English" latlng="17.05,-61.8" name="Antigua and Barbuda"
		population="86295" region="Americas" subregion="Caribbean" />
	<country capital="Canberra" cca3="AUS" currency="AUD"
		languages="English" latlng="-27,133" name="Australia"
		population="23254142" region="Oceania"
		subregion="Australia and New Zealand" />
	<country capital="Vienna" cca3="AUT" currency="EUR"
		languages="Austro-Bavarian German" latlng="47.33333333,13.33333333"
		name="Austria" population="8501502" region="Europe"
		subregion="Western Europe">
		<border>CZE</border>
		<border>DEU</border>
		<border>HUN</border>
		<border>ITA</border>
		<border>LIE</border>
		<border>SVK</border>
		<border>SVN</border>
		<border>CHE</border>
	</country>
	<country capital="Baku" cca3="AZE" currency="AZN"
		languages="Azerbaijani,Russian" latlng="40.5,47.5" name="Azerbaijan"
		population="9235100" region="Asia" subregion="Western Asia">
		<border>ARM</border>
		<border>GEO</border>
		<border>IRN</border>
		<border>RUS</border>
		<border>TUR</border>
	</country>
	<country capital="Bujumbura" cca3="BDI" currency="BIF"
		languages="French,Kirundi" latlng="-3.5,30" name="Burundi"
		population="10163000" region="Africa" subregion="Eastern Africa">
		<border>COD</border>
		<border>RWA</border>
		<border>TZA</border>
	</country>
	<country capital="Brussels" cca3="BEL" currency="EUR"
		languages="German,French,Dutch" latlng="50.83333333,4" name="Belgium"
		population="11175653" region="Europe" subregion="Western Europe">
		<border>FRA</border>
		<border>DEU</border>
		<border>LUX</border>
		<border>NLD</border>
	</country>
	<country capital="Porto-Novo" cca3="BEN" currency="XOF"
		languages="French" latlng="9.5,2.25" name="Benin"
		population="10323000" region="Africa" subregion="Western Africa">
		<border>BFA</border>
		<border>NER</border>
		<border>NGA</border>
		<border>TGO</border>
	</country>
	<country capital="Ouagadougou" cca3="BFA" currency="XOF"
		languages="French" latlng="13,-2" name="Burkina Faso"
		population="17322796" region="Africa" subregion="Western Africa">
		<border>BEN</border>
		<border>CIV</border>
		<border>GHA</border>
		<border>MLI</border>
		<border>NER</border>
		<border>TGO</border>
	</country>
	<country capital="Dhaka" cca3="BGD" currency="BDT"
		languages="Bengali" latlng="24,90" name="Bangladesh"
		population="152518015" region="Asia" subregion="Southern Asia">
		<border>MMR</border>
		<border>IND</border>
	</country>
	<country capital="Sofia" cca3="BGR" currency="BGN"
		languages="Bulgarian" latlng="43,25" name="Bulgaria"
		population="7282041" region="Europe" subregion="Eastern Europe">
		<border>GRC</border>
		<border>MKD</border>
		<border>ROU</border>
		<border>SRB</border>
		<border>TUR</border>
	</country>
	<country capital="Manama" cca3="BHR" currency="BHD"
		languages="Arabic" latlng="26,50.55" name="Bahrain"
		population="1234571" region="Asia" subregion="Western Asia" />
	<country capital="Nassau" cca3="BHS" currency="BSD"
		languages="English" latlng="24.25,-76" name="Bahamas"
		population="319031" region="Americas" subregion="Caribbean" />
	<country capital="Sarajevo" cca3="BIH" currency="BAM"
		languages="Bosnian,Croatian,Serbian" latlng="44,18"
		name="Bosnia and Herzegovina" population="3791622" region="Europe"
		subregion="Southern Europe">
		<border>HRV</border>
		<border>MNE</border>
		<border>SRB</border>
	</country>
	<country capital="Gustavia" cca3="BLM" currency="EUR"
		languages="French" latlng="18.5,-63.41666666" name="Saint Barthélemy"
		population="8938" region="Americas" subregion="Caribbean" />
	<country capital="Jamestown" cca3="SHN" currency="SHP,GBP"
		languages="English" latlng="-15.95,-5.72" name="Saint Helena"
		population="4255" region="Africa" subregion="Western Africa" />
	<country capital="Minsk" cca3="BLR" currency="BYN"
		languages="Belarusian,Russian" latlng="53,28" name="Belarus"
		population="9465500" region="Europe" subregion="Eastern Europe">
		<border>LVA</border>
		<border>LTU</border>
		<border>POL</border>
		<border>RUS</border>
		<border>UKR</border>
	</country>
	<country capital="Belmopan" cca3="BLZ" currency="BZD"
		languages="Belizean Creole,English,Spanish" latlng="17.25,-88.75"
		name="Belize" population="312971" region="Americas"
		subregion="Central America">
		<border>GTM</border>
		<border>MEX</border>
	</country>
	<country capital="Hamilton" cca3="BMU" currency="BMD"
		languages="English" latlng="32.33333333,-64.75" name="Bermuda"
		population="64237" region="Americas" subregion="Northern America" />
	<country capital="Sucre" cca3="BOL" currency="BOB,BOV"
		languages="Aymara,Guaraní,Quechua,Spanish" latlng="-17,-65"
		name="Bolivia" population="10027254" region="Americas"
		subregion="South America">
		<border>ARG</border>
		<border>BRA</border>
		<border>CHL</border>
		<border>PRY</border>
		<border>PER</border>
	</country>
	<country cca3="BES" currency="USD"
		languages="English,Dutch,Papiamento" latlng="12.18,-68.25"
		name="Bonaire" population="17408" region="Americas"
		subregion="Caribbean" />
	<country capital="Brasília" cca3="BRA" currency="BRL"
		languages="Portuguese" latlng="-10,-55" name="Brazil"
		population="201032714" region="Americas" subregion="South America">
		<border>ARG</border>
		<border>BOL</border>
		<border>COL</border>
		<border>GUF</border>
		<border>GUY</border>
		<border>PRY</border>
		<border>PER</border>
		<border>SUR</border>
		<border>URY</border>
		<border>VEN</border>
	</country>
	<country capital="Bridgetown" cca3="BRB" currency="BBD"
		languages="English" latlng="13.16666666,-59.53333333" name="Barbados"
		population="274200" region="Americas" subregion="Caribbean" />
	<country capital="Bandar Seri Begawan" cca3="BRN"
		currency="BND" languages="Malay" latlng="4.5,114.66666666"
		name="Brunei" population="393162" region="Asia"
		subregion="South-Eastern Asia">
		<border>MYS</border>
	</country>
	<country capital="Thimphu" cca3="BTN" currency="BTN,INR"
		languages="Dzongkha" latlng="27.5,90.5" name="Bhutan"
		population="740990" region="Asia" subregion="Southern Asia">
		<border>CHN</border>
		<border>IND</border>
	</country>
	<country cca3="BVT" currency="NOK" languages="Norwegian"
		latlng="-54.43333333,3.4" name="Bouvet Island" population="0"
		region="Antarctic" />
	<country capital="Gaborone" cca3="BWA" currency="BWP"
		languages="English,Tswana" latlng="-22,24" name="Botswana"
		population="2024904" region="Africa" subregion="Southern Africa">
		<border>NAM</border>
		<border>ZAF</border>
